name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gar:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: project-users-backend
      PROJECT_ID: final-project-407919
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
        export_default_credentials: true

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
        
    - name: Build Docker Image
      run: docker build -t "${{ env.IMAGE_NAME }}:latest" .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker southamerica-east1.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag '${{ env.IMAGE_NAME }}:latest' 'southamerica-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:latest'
        docker push '${{ env.IMAGE_NAME }}:latest' 'southamerica-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:latest'
